In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [29]:
tokens = ["I", "love", "deep", "learning"]

In [30]:
embedding_dim = 4
np.random.seed(42)
X = np.random.rand(len(tokens), embedding_dim)  # shape: (4, 4)

In [31]:
W_q = np.random.rand(embedding_dim, embedding_dim)
W_k = np.random.rand(embedding_dim, embedding_dim)
W_v = np.random.rand(embedding_dim, embedding_dim)

In [32]:
Q = X @ W_q  # shape: (4, 4)
K = X @ W_k
V = X @ W_v

In [33]:
d_k = embedding_dim
scores = Q @ K.T / np.sqrt(d_k)

In [34]:
def softmax(x):
    exps = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exps / np.sum(exps, axis=-1, keepdims=True)


In [35]:
weights = softmax(scores)
output = weights @ V
output

array([[1.1796727 , 0.9217873 , 1.45815851, 1.33770808],
       [1.09435999, 0.83851284, 1.39301108, 1.243537  ],
       [1.1515616 , 0.89314997, 1.43845963, 1.30643711],
       [1.11065168, 0.85384713, 1.40560424, 1.26208253]])

In [36]:
weights

array([[0.37375874, 0.11373439, 0.33710375, 0.17540311],
       [0.30050337, 0.18229358, 0.29603114, 0.22117191],
       [0.34464159, 0.13464245, 0.32827962, 0.19243634],
       [0.31362022, 0.1663662 , 0.30402174, 0.21599184]])

Change the input embeddings or weight matrices

In [37]:
X = np.random.rand(len(tokens), embedding_dim)


In [38]:
Q = X @ W_q
K = X @ W_k
V = X @ W_v

In [39]:
d_k = embedding_dim
scores = Q @ K.T / np.sqrt(d_k)
weights = softmax(scores)
output = weights @ V
output

array([[0.96312871, 0.83955808, 1.04647951, 1.11597329],
       [0.96597852, 0.84397694, 1.04777827, 1.11854938],
       [0.96845362, 0.84730424, 1.04845223, 1.12040088],
       [0.95361734, 0.82600822, 1.04555943, 1.1081502 ]])

weights

In [40]:
weights

array([[0.24848274, 0.25406103, 0.27830727, 0.21914895],
       [0.24239569, 0.2492099 , 0.29302445, 0.21536995],
       [0.24415681, 0.2517607 , 0.29365392, 0.21042857],
       [0.24822995, 0.24266956, 0.27247446, 0.23662602]])

"deep" is the most important token


changing embeddings changes how queries and keys interact